### PR TITLE
Update all Uniswap references to Vexchange in v2 docs

### PR DESCRIPTION
**Pull request by andersonaguiar**
Ticket: https://trello.com/c/vIaeAssO/14-update-all-uniswap-references-to-vexchange-in-v2-docs

### CODE REVIEW

**Comment by KennethAshley** [comment]
I saw a few more uniswap references from doing a global search. Killer work on this though man. thanks a bunch!

**Comment by andersonaguiar** [comment]
We need to update the [`Factory page`](https://docs.vexchange.io/docs/v2/smart-contracts/factory/)

A lot of Ethereum related, I updated only the factory contract link.

**Comment by andersonaguiar** [comment]
We also need to rework the Governance page: https://docs.vexchange.io/docs/v2/governance/overview/

**Comment by xenide** [comment]
Under the SDK section, I think there are still references to `WETH` which can be changed to `WVET`. 

Also I think we can change all the `VVET` (old name) references to `WVET`

**Comment by xenide** [comment]
Looks good, thanks for the refactor 🙏

For the router02 page, there are references to ETH instead of VET. Can refer to [this file](https://github.com/vexchange/vexchange-contracts/blob/main/vexchange-v2-periphery/contracts/VexchangeV2Router02.sol) to see that all the ETH has been replaced with VET
 
But this is not high priority at all, can be done much later if at all.

**Review by xenide — APPROVED** [review]

**Review by KennethAshley — APPROVED** [review]
🔥

**Pull request merged**
